# Generated by Django 3.1.4 on 2021-01-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='naive_user',
            fields=[
                ('n_username', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('n_name', models.CharField(max_length=200, null=True)),
                ('n_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=200, null=True)),
                ('n_dob', models.DateTimeField(null=True)),
                ('n_age', models.IntegerField(null=True)),
                ('n_address', models.TextField(null=True)),
                ('n_email', models.EmailField(max_length=254, null=True)),
                ('n_contact', models.BigIntegerField(null=True)),
                ('n_datecreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('n_medicalhistory', models.TextField(null=True)),
                ('n_sideeffects', models.TextField(null=True)),
                ('n_priscription', models.TextField(null=True)),
                ('n_remarks', models.TextField(null=True)),
            ],
        ),
    ]
