# Generated by Django 3.1.4 on 2021-01-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_datecreated',
            new_name='datecreated',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_medicalhistory',
            new_name='medicalhistory',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_priscription',
            new_name='priscription',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_remarks',
            new_name='remarks',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_sideeffects',
            new_name='sideeffects',
        ),
        migrations.RenameField(
            model_name='naive_user',
            old_name='n_username',
            new_name='username',
        ),
    ]
